id: IEAA41BB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:19:13+00:00'
last_modified: '2022-06-08T12:03:30.147773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22113
  title: བྱང་གཏེར་ཕུར་པའི་འཕྲིན་ལས་རྒྱས་པ་དང་ཆོས་སྲུང་བསྐང་གསོའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF6C:
      image_group_id: I1KG10389
      title: ''
      total_pages: 344
      order: 1
      base_file: BF6C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
