id: P009583
initial_creation_type: ocr
source_metadata:
  id: bdr:W22113
  title: བྱང་གཏེར་ཕུར་པའི་འཕྲིན་ལས་རྒྱས་པ་དང་ཆོས་སྲུང་བསྐང་གསོའི་སྐོར།
  author: ''
  volumes:
    d68af1f0b9c341238642226408522043:
      image_group_id: I1KG10389
      title: ''
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
